CREATE TABLE [dbo].[LandIoriginal] (
    [LAND KEY NUMBER]            VARCHAR (50)  NULL,
    [UNIQUE PROPERTY CODE]       VARCHAR (50)  NULL,
    [PROP_TYPE]                  VARCHAR (50)  NULL,
    [PARCEL]                     VARCHAR (50)  NULL,
    [PORTION]                    VARCHAR (50)  NULL,
    [FARM NAME]                  VARCHAR (MAX) NULL,
    [LAND LOC]                   VARCHAR (50)  NULL,
    [FACILITY NAME]              VARCHAR (MAX) NULL,
    [ OPENNING BALANCE 2018 ]    VARCHAR (50)  NULL,
    [ ADDITIONS 2018 ]           VARCHAR (50)  NULL,
    [ VALUE ADJUSTMENT 2018 ]    VARCHAR (50)  NULL,
    [ PPEA(IN) 2018 ]            VARCHAR (50)  NULL,
    [ PPEA(OUT) 2018 ]           VARCHAR (50)  NULL,
    [ DISPOSALS 2018 ]           VARCHAR (50)  NULL,
    [ CLOSING BALANCE 2018 ]     VARCHAR (50)  NULL,
    [Column 15]                  VARCHAR (50)  NULL,
    [ OPENNING BALANCE 2019 ]    VARCHAR (50)  NULL,
    [ ADDITIONS 2019 ]           VARCHAR (50)  NULL,
    [ DISPOSALS 2019 ]           VARCHAR (50)  NULL,
    [ CLOSING BALANCE 2019 ]     VARCHAR (50)  NULL,
    [ DATE OF VALUATION ]        VARCHAR (50)  NULL,
    [FACILITY TYPE]              VARCHAR (50)  NULL,
    [STREET NAME]                VARCHAR (MAX) NULL,
    [SUBURB]                     VARCHAR (50)  NULL,
    [TOWN]                       VARCHAR (50)  NULL,
    [PROVINCE]                   VARCHAR (50)  NULL,
    [DEEDS OFFICE]               VARCHAR (50)  NULL,
    [MAGISTERIAL DISTRICT]       VARCHAR (50)  NULL,
    [DISTRICT MUNICIPALITY]      VARCHAR (50)  NULL,
    [LOCAL MUNICIPALITY]         VARCHAR (50)  NULL,
    [TITLE DEEDS]                VARCHAR (50)  NULL,
    [SG DIAGRAM]                 VARCHAR (50)  NULL,
    [AREA_(HA)]                  VARCHAR (50)  NULL,
    [REG OWNER]                  VARCHAR (MAX) NULL,
    [OWNERSHIP CATEGORY]         VARCHAR (50)  NULL,
    [ZONING]                     VARCHAR (50)  NULL,
    [REG DIVISION]               VARCHAR (50)  NULL,
    [DATE REGISTRATION]          VARCHAR (50)  NULL,
    [USER DEPT]                  VARCHAR (50)  NULL,
    [CONDTION RATING]            VARCHAR (50)  NULL,
    [INTEND USE OF THE PROPERTY] VARCHAR (50)  NULL,
    [CURRENT USE]                VARCHAR (50)  NULL,
    [GPS COORDINATES SOUTH]      VARCHAR (50)  NULL,
    [GPS COORDINATES EAST]       VARCHAR (50)  NULL,
    [VESTING INFORMATION]        VARCHAR (50)  NULL,
    [COMMENTS]                   VARCHAR (MAX) NULL
);

