CREATE TABLE [dbo].[NonResidentialFacilities] (
    [Id]                     INT           IDENTITY (1, 1) NOT NULL,
    [Name]                   VARCHAR (100) NULL,
    [ClientCode]             VARCHAR (100) NULL,
    [PropType]               VARCHAR (100) NULL,
    [Parcel]                 VARCHAR (100) NULL,
    [Portion]                VARCHAR (100) NULL,
    [FarmName]               VARCHAR (100) NULL,
    [LandLoc]                VARCHAR (100) NULL,
    [Type]                   VARCHAR (100) NULL,
    [ValuationDate]          VARCHAR (100) NULL,
    [SGDiagram]              VARCHAR (100) NULL,
    [AreaHA]                 VARCHAR (100) NULL,
    [RegOwner]               VARCHAR (100) NULL,
    [OwnershipCategory]      VARCHAR (100) NULL,
    [Zoning]                 VARCHAR (100) NULL,
    [RegDivision]            VARCHAR (100) NULL,
    [UserDept]               VARCHAR (100) NULL,
    [ConditionRating]        VARCHAR (100) NULL,
    [IntendUseOfTheProperty] VARCHAR (100) NULL,
    [CurrentUse]             VARCHAR (100) NULL,
    [GPSCoordinatesSouth]    VARCHAR (100) NULL,
    [GPSCoordinatesEast]     VARCHAR (100) NULL,
    [VestingInformation]     VARCHAR (100) NULL,
    [Comments]               VARCHAR (MAX) NULL,
    [UserId]                 INT           NOT NULL,
    [Status]                 INT           NOT NULL,
    [CreatedBy]              INT           NOT NULL,
    [CreatedDate]            DATETIME      NOT NULL,
    [ModifiedBy]             INT           NULL,
    [ModifiedDate]           DATETIME      NULL,
    CONSTRAINT [PK_NonResidentialFacilities_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

